### ISSUE TITLE
Cruizcore doubt: Calculate the distance

### ISSUE THREAD

**Issue by jabrena** [bmegli/ev3dev-mapping#13]
Hi @bmegli,

I am trying to calculate the distance reached using 2 motors with the help of the Cruizcore sensor and I would like to know if you know how to calculate the distance using the ACC_X & ACC_Y from the sensor.

Imagine that the robot move the motors straight 5 seconds and it is possible to store initial acceleration for X Axis and Y Axis.

I am not sure if you had this doubt.

Cheers

Juan Antonio

**Comment by bmegli** [comment]
Hi @jabrena,

I would say - don't calculate it using the accelerometer, calculate it using the gyroscope.

Specifically calculate it using the accumalated angle that CruizCore calculates internally with Kalman Filter. 

We have already discussed it in #1.
Lauro covers it at [robotnav](http://www.robotnav.com/).
You also have the formulas in the youtube [video](https://www.youtube.com/watch?v=vzND_ISdhEs)

--------------------------------------------------------------------------------------

But if you insist on calculations with the accelerometer...

The short answer is integrate it twice . 

The long answer is...

Assuming that acceleration in short timeframe is constant (average at timeframe start & end)

Assume x=0, y=0, Vx=0, Vy=0, Ax=0, Ay=0

At each timepoint:
- read acceleration Ax, Ay
- calculate average acceleration in this timeframe from previous Ax, Ay and current
- calculate Vx and Vy change from average Ax, Ay (speed change = accelaration * time passed)
- calculate average Vx and Vy in this timeframe from previous Vx, Vy and Vx, Vy change
- calculate x and y change from average Vx and Vy in this frame
- update x and y using this change

Anyway, under constant acceleration model in timeframe you can use formulas from primary school (s=V0*t + a*t^2/2 or something like that) which should be equivalent to the above.

 Now - why this is evil (you know - like the Sauron):
- you integrate twice, the error accumulates
- earth gravity will corrupt Ax and Ay on uneven ground, if robot shakes or if your device is not ideally placed and earth gravity is big
- shaking will also provide noise to readings
- the time you measure will be innacurate for 2 reasons
  - you don't know when exactly OS wakes you up
  - reading CruizCore on I2C takes around 10 ms so you don't know when precisely the acceleration was measured

Nonetheless this will work to some extent (but the errors and noise will be big).

Now - you naturally can use more refined model (e.g. constant acceleration of acceleration) but I doubt it will be of much help. 

You can always try and check - then I am interested how it works ;-)

**Comment by bmegli** [comment]
Some more elaboration why integrating twice is evil.

When you integrate once you get speed. You update speed with imperfect value. The error accumulates (unbounded!) in time.

Now you integrate the second time to get displacement. The errors of speed grow all the time and all the time you introduce this growing error to your position calculation when integrating speed.

So the interesting thing is that this could actually work well in a short timeframe. E.g - compare distance traveled this way with distance from the motors. If they differ wildly you have probably hit something and the motors are wrong.

**Comment by jabrena** [comment]
Hi mate, I will begin with Gyro formulas from the video.

Serious work!
https://pbs.twimg.com/media/CuB8WXvWIAAc1Sc.jpg

Do you integrate motion model from IMU with motion model for motor using Kalman?

Cheers

**Comment by bmegli** [comment]
> Do you integrate motion model from IMU with motion model for motor using Kalman?

No

**Comment by jabrena** [comment]
Hi @bmegli ,

In the image about the motion model:
https://pbs.twimg.com/media/CuB8WXvWIAAc1Sc.jpg

How to calculate the displacement using data from Gyro?
In the case of a Servo Motor, I am using the calculus that we have discussed previously but for Gyro?

Cheers

Juan Antonio

**Comment by bmegli** [comment]
@jabrena 

> How to calculate the displacement using data from Gyro?

You don't.

You calculate displacement from motor data. You take the heading from the gyroscope.

I have answered  that (to you) at least 3 times in #1:
- with formulas
- with algorithm
- with video scheme

I have also pointed you to resources where it is further explained (robotnav).

Read up #1 and resources if you still have doubts.

**Comment by jabrena** [comment]
Hi @bmegli,

Finally, I understood the formulas. 
Many thanks mate

Cheers

**Comment by jabrena** [comment]
Many thanks for the support. I have released this EV3G Custom blocks with your help.
https://github.com/ilovenetruinos/ev3g-odometry

My sincere thanks.

Cheers

Juan Antonio
