### ISSUE TITLE
Trigonometry algorithm issue 

### ISSUE THREAD

**Issue by Gamma-Software** [bmegli/ev3dev-mapping#4]
Hi,
I saw your tutorial on using the Lidar NXV11 and particulary your algorithm used to calculate the angle Alpha from the angle Phi. 
`double alpha = 180 - 82 + angle;` Line 261 from MainWindow.xaml.cs
I know that the sum of the angles in a triangle is 180° so it should be `double alpha = 180 - 82 - angle;`
Regards ;) 
Valentin Rudloff

**Comment by bmegli** [comment]
Hi Gamma-Software,

Thanks for the comment.

This formula comes from:
- http://www.robotshop.com/media/files/PDF/revolds-whitepaper.pdf
- and from Neato patent US8996172

It's for Revo LDS. You can get it working with XV11 LIDAR by manipulating the correction signs.

As for the formula itself, you have to keep in mind that those are oriented angles.

How about if we draw it like in *attached scheme* where all the angles are positive?
 
![scheme](https://cloud.githubusercontent.com/assets/9095769/15454140/e3552704-202f-11e6-8872-14f6801a77e6.png)

Now we have alpha=beta - phi

XV11 has geometyry like in attached *xv11* photo without cover.

![xv11](https://cloud.githubusercontent.com/assets/9095769/15454161/490df67a-2030-11e6-8069-233195e66630.png)

To adapt the formula for XV11 you would still have to take into account its geometry. For phi=0 you would have to add the correction for x and subtract for y. 

You can write this in concise manner as alfa= - (beta-phi) and add the correction.

In fact the above is the most concise way I found for XV11.

You can test it all here:

https://github.com/bmegli/ev3dev-mapping/blob/master/xv11test/xv11plot.ods

Where you have phi/distance data captured from XV11 in a small rectangular box.

The formulas there have different coordinate system there (Y axis as ahead of XV11) but you can change them.

**Comment by bmegli** [comment]
Another notes:
- when taking coordinate system with Y along longer axis of LIDAR you have to rotate everything 90 degree CCW. This corresponds to changing X to Y/ Y to X and changing X sign.
- when plotting on screen in the code the Y axis is naturally inverted (screen coordinates).

So all of that is taken into account.

If you have any simplier idea how to explain the correction needed for XV11 I will happily read.

**Comment by Gamma-Software** [comment]
Hi @bmegli :)
Thanks taking your time explaining me a little bit of your code, I really appreciate. Yes I understand now how it works. When I make the correction on the spreadsheet of what I supposed it was the right solution, the representation of the map started to skew a bit. 
So it seem that it's about the axis taken.
If I have some more questions I'll be there to ask you ;)

**Comment by bmegli** [comment]
You're welcome @Gamma-Software,

For the record - I had similiar doubts about formula from Revo LDS paper (yes, why had they chosen this alfa, is this a mistake?) but then I took a scan in  small rectangular box and simply checked what is the right correction.

**Comment by bmegli** [comment]
In case you have some more questions just ask!

This issue is for:

[ev3dev-mapping-abandoned](https://github.com/bmegli/ev3dev-mapping-abandoned)

and is dead for months so I am closing it.

**Comment by Gamma-Software** [comment]
No that's good @bmegli ;) Thanks for your answer.
