### ISSUE TITLE
Make maps reusable in future sessions

### ISSUE THREAD

**Issue by bmegli** [bmegli/ev3dev-mapping#9]
Maps made in one session should be reuseable in future sessions.

This will let: 
- using map created by one robot by other robots without laser (just the odometry)
- build maps from fragments
- compare mappings overlaid (build with different methods)

Ideally to just drag saved map to Unity designer and position it with transform.

Problem - Unity doesn't support point clouds.

We already have the shader so this should not be too difficult.

**Comment by jabrena** [comment]
Did you test ROS?

**Comment by bmegli** [comment]
Nice to see you again @jabrena,

I can't see how this connects with this issue.

If you need ROS just install it.

**Comment by jabrena** [comment]
Hi,

maybe exist a ROS feature to store maps and reuse later. Should exist in ROS ecosystem.

The last video about mapping was fantastic with 2 LIDARs

Juan Antonio

**Comment by bmegli** [comment]
Oh, you mean that.

I don't need ROS dependency. 

This is simple issue,

I already have the data-model and shader for visualizaing it in Unity used during runtime (mapping)

I need only support to add result during design-time.

> The last video about mapping was fantastic with 2 LIDARs

Thanks! I suppose some fragments were embarrassing (LOTR), but that's just me ;-))))

**Comment by jabrena** [comment]
Did you see Cartographer?
https://github.com/googlecartographer/cartographer

**Comment by bmegli** [comment]
Interesting.

In the article they even made some tests with xv11lidar (not directly but getting scans from neato debug interface), also they used different scenario (pushing neato on trolley). 

The map is not perfect (some submaps are clearly missaligned) but it's nontheless impressive.
